In [1]:
# value_counts()

In [52]:
import pandas as pd
import numpy as np

excel_file = pd.read_excel(r"C:\Users\adead\Downloads\excel dataset for practice\Financial Sample.xlsx")

df = pd.DataFrame(excel_file)
df.tail(60)
#df.info()

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
640,Midmarket,Canada,Paseo,High,1743.0,10,15,26145.0,3660.30,22484.70,17430.0,5054.70,2013-10-01,10,October,2013
641,Channel Partners,United States of America,Paseo,High,2914.0,10,12,34968.0,4895.52,30072.48,8742.0,21330.48,2014-10-01,10,October,2014
642,Government,France,Paseo,High,1731.0,10,7,12117.0,1696.38,10420.62,8655.0,1765.62,2014-10-01,10,October,2014
643,Government,Canada,Paseo,High,700.0,10,350,245000.0,34300.00,210700.00,182000.0,28700.00,2014-11-01,11,November,2014
644,Channel Partners,Canada,Paseo,High,2222.0,10,12,26664.0,3732.96,22931.04,6666.0,16265.04,2013-11-01,11,November,2013
645,Government,United States of America,Paseo,High,1177.0,10,350,411950.0,57673.00,354277.00,306020.0,48257.00,2014-11-01,11,November,2014
646,Government,France,Paseo,High,1922.0,10,350,672700.0,94178.00,578522.00,499720.0,78802.00,2013-11-01,11,November,2013
647,Enterprise,Mexico,Velo,High,1575.0,120,125,196875.0,27562.50,169312.50,189000.0,-19687.50,2014-02-01,2,February,2014
648,Government,United States of America,Velo,High,606.0,120,20,12120.0,1696.80,10423.20,6060.0,4363.20,2014-04-01,4,April,2014
649,Small Business,United States of America,Velo,High,2460.0,120,300,738000.0,103320.00,634680.00,615000.0,19680.00,2014-07-01,7,July,2014
650,Small Business,Canada,Velo,High,269.0,120,300,80700.0,11298.00,69402.00,67250.0,2152.00,2013-10-01,10,October,2013
651,Small Business,Germany,Velo,High,2536.0,120,300,760800.0,106512.00,654288.00,634000.0,20288.00,2013-11-01,11,November,2013
652,Government,Mexico,VTT,High,2903.0,250,7,20321.0,2844.94,17476.06,14515.0,2961.06,2014-03-01,3,March,2014
653,Small Business,United States of America,VTT,High,2541.0,250,300,762300.0,106722.00,655578.00,635250.0,20328.00,2014-08-01,8,August,2014
654,Small Business,Canada,VTT,High,269.0,250,300,80700.0,11298.00,69402.00,67250.0,2152.00,2013-10-01,10,October,2013
655,Small Business,Canada,VTT,High,1496.0,250,300,448800.0,62832.00,385968.00,374000.0,11968.00,2014-10-01,10,October,2014
656,Small Business,United States of America,VTT,High,1010.0,250,300,303000.0,42420.00,260580.00,252500.0,8080.00,2014-10-01,10,October,2014
657,Government,France,VTT,High,1281.0,250,350,448350.0,62769.00,385581.00,333060.0,52521.00,2013-12-01,12,December,2013
658,Small Business,Canada,Amarilla,High,888.0,260,300,266400.0,37296.00,229104.00,222000.0,7104.00,2014-03-01,3,March,2014
659,Enterprise,United States of America,Amarilla,High,2844.0,260,125,355500.0,49770.00,305730.00,341280.0,-35550.00,2014-05-01,5,May,2014
660,Channel Partners,France,Amarilla,High,2475.0,260,12,29700.0,4158.00,25542.00,7425.0,18117.00,2014-08-01,8,August,2014
661,Midmarket,Canada,Amarilla,High,1743.0,260,15,26145.0,3660.30,22484.70,17430.0,5054.70,2013-10-01,10,October,2013
662,Channel Partners,United States of America,Amarilla,High,2914.0,260,12,34968.0,4895.52,30072.48,8742.0,21330.48,2014-10-01,10,October,2014
663,Government,France,Amarilla,High,1731.0,260,7,12117.0,1696.38,10420.62,8655.0,1765.62,2014-10-01,10,October,2014
664,Government,Mexico,Amarilla,High,1727.0,260,7,12089.0,1692.46,10396.54,8635.0,1761.54,2013-10-01,10,October,2013
665,Midmarket,Mexico,Amarilla,High,1870.0,260,15,28050.0,3927.00,24123.00,18700.0,5423.00,2013-11-01,11,November,2013
666,Enterprise,France,Carretera,High,1174.0,3,125,146750.0,22012.50,124737.50,140880.0,-16142.50,2014-08-01,8,August,2014
667,Enterprise,Germany,Carretera,High,2767.0,3,125,345875.0,51881.25,293993.75,332040.0,-38046.25,2014-08-01,8,August,2014
668,Enterprise,Germany,Carretera,High,1085.0,3,125,135625.0,20343.75,115281.25,130200.0,-14918.75,2014-10-01,10,October,2014
669,Small Business,Mexico,Montana,High,546.0,5,300,163800.0,24570.00,139230.00,136500.0,2730.00,2014-10-01,10,October,2014
670,Government,Germany,Paseo,High,1158.0,10,20,23160.0,3474.00,19686.00,11580.0,8106.00,2014-03-01,3,March,2014
671,Midmarket,Canada,Paseo,High,1614.0,10,15,24210.0,3631.50,20578.50,16140.0,4438.50,2014-04-01,4,April,2014
672,Government,Mexico,Paseo,High,2535.0,10,7,17745.0,2661.75,15083.25,12675.0,2408.25,2014-04-01,4,April,2014
673,Government,Mexico,Paseo,High,2851.0,10,350,997850.0,149677.50,848172.50,741260.0,106912.50,2014-05-01,5,May,2014
674,Midmarket,Canada,Paseo,High,2559.0,10,15,38385.0,5757.75,32627.25,25590.0,7037.25,2014-08-01,8,August,2014
675,Government,United States of America,Paseo,High,267.0,10,20,5340.0,801.00,4539.00,2670.0,1869.00,2013-10-01,10,October,2013
676,Enterprise,Germany,Paseo,High,1085.0,10,125,135625.0,20343.75,115281.25,130200.0,-14918.75,2014-10-01,10,October,2014
677,Midmarket,Germany,Paseo,High,1175.0,10,15,17625.0,2643.75,14981.25,11750.0,3231.25,2014-10-01,10,October,2014
678,Government,United States of America,Paseo,High,2007.0,10,350,702450.0,105367.50,597082.50,521820.0,75262.50,2013-11-01,11,November,2013
679,Government,Mexico,Paseo,High,2151.0,10,350,752850.0,112927.50,639922.50,559260.0,80662.50,2013-11-01,11,November,2013
680,Channel Partners,United States of America,Paseo,High,914.0,10,12,10968.0,1645.20,9322.80,2742.0,6580.80,2014-12-01,12,December,2014
681,Government,France,Paseo,High,293.0,10,20,5860.0,879.00,4981.00,2930.0,2051.00,2014-12-01,12,December,2014
682,Channel Partners,Mexico,Velo,High,500.0,120,12,6000.0,900.00,5100.00,1500.0,3600.00,2014-03-01,3,March,2014
683,Midmarket,France,Velo,High,2826.0,120,15,42390.0,6358.50,36031.50,28260.0,7771.50,2014-05-01,5,May,2014
684,Enterprise,France,Velo,High,663.0,120,125,82875.0,12431.25,70443.75,79560.0,-9116.25,2014-09-01,9,September,2014
685,Small Business,United States of America,Velo,High,2574.0,120,300,772200.0,115830.00,656370.00,643500.0,12870.00,2013-11-01,11,November,2013
686,Enterprise,United States of America,Velo,High,2438.0,120,125,304750.0,45712.50,259037.50,292560.0,-33522.50,2013-12-01,12,December,2013
687,Channel Partners,United States of America,Velo,High,914.0,120,12,10968.0,1645.20,9322.80,2742.0,6580.80,2014-12-01,12,December,2014
688,Government,Canada,VTT,High,865.5,250,20,17310.0,2596.50,14713.50,8655.0,6058.50,2014-07-01,7,July,2014
689,Midmarket,Germany,VTT,High,492.0,250,15,7380.0,1107.00,6273.00,4920.0,1353.00,2014-07-01,7,July,2014
690,Government,United States of America,VTT,High,267.0,250,20,5340.0,801.00,4539.00,2670.0,1869.00,2013-10-01,10,October,2013
691,Midmarket,Germany,VTT,High,1175.0,250,15,17625.0,2643.75,14981.25,11750.0,3231.25,2014-10-01,10,October,2014
692,Enterprise,Canada,VTT,High,2954.0,250,125,369250.0,55387.50,313862.50,354480.0,-40617.50,2013-11-01,11,November,2013
693,Enterprise,Germany,VTT,High,552.0,250,125,69000.0,10350.00,58650.00,66240.0,-7590.00,2014-11-01,11,November,2014
694,Government,France,VTT,High,293.0,250,20,5860.0,879.00,4981.00,2930.0,2051.00,2014-12-01,12,December,2014
695,Small Business,France,Amarilla,High,2475.0,260,300,742500.0,111375.00,631125.00,618750.0,12375.00,2014-03-01,3,March,2014
696,Small Business,Mexico,Amarilla,High,546.0,260,300,163800.0,24570.00,139230.00,136500.0,2730.00,2014-10-01,10,October,2014
697,Government,Mexico,Montana,High,1368.0,5,7,9576.0,1436.40,8139.60,6840.0,1299.60,2014-02-01,2,February,2014
698,Government,Canada,Paseo,High,723.0,10,7,5061.0,759.15,4301.85,3615.0,686.85,2014-04-01,4,April,2014
699,Channel Partners,United States of America,VTT,High,1806.0,250,12,21672.0,3250.80,18421.20,5418.0,13003.20,2014-05-01,5,May,2014

In [53]:
# Counting distinct values in desceding order (default) for a specific column
df['Discount Band'].value_counts()

Discount Band
High      245
Medium    242
Low       160
Name: count, dtype: int64

In [54]:
# counting in ascending order (by default, ascending = False)
# SHIFT + TAB

df['Discount Band'].value_counts(ascending=True)

Discount Band
Low       160
Medium    242
High      245
Name: count, dtype: int64

In [40]:
# counting NaN too. (by default, dropna=True)

df['Discount Band'].value_counts(dropna=False, ascending=True)

Discount Band
NaN        53
Low       160
Medium    242
High      245
Name: count, dtype: int64

In [42]:
# percentage or relative frequency (by default, normalize=False)

df['Discount Band'].value_counts(dropna=False, ascending=True, normalize=True)

Discount Band
NaN       0.075714
Low       0.228571
Medium    0.345714
High      0.350000
Name: proportion, dtype: float64

In [55]:
# Using value_counts() for a specific value (rather than a column)
df['Discount Band'].value_counts(dropna=False, ascending=True)['Medium']

np.int64(242)

In [57]:
# Counting unique values - size
df.groupby('Discount Band').size()  # the same as .value_counts()

Discount Band
High      245
Low       160
Medium    242
dtype: int64

In [58]:
# print out counts by each column
df.groupby('Discount Band').count()

,Segment,Country,Product,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
Discount Band,,,,,,,,,,,,,,,
High,245,245,245,245,245,245,245,245,245,245,245,245,245,245,245
Low,160,160,160,160,160,160,160,160,160,160,160,160,160,160,160
Medium,242,242,242,242,242,242,242,242,242,242,242,242,242,242,242

In [61]:
# apply()
df.apply(pd.value_counts)

C:\Users\adead\AppData\Local\Temp\ipykernel_5820\2427318911.py:2: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  df.apply(pd.value_counts)
C:\Users\adead\AppData\Local\Temp\ipykernel_5820\2427318911.py:2: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  df.apply(pd.value_counts)
C:\Users\adead\AppData\Local\Temp\ipykernel_5820\2427318911.py:2: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  df.apply(pd.value_counts)
C:\Users\adead\AppData\Local\Temp\ipykernel_5820\2427318911.py:2: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  df.apply(pd.value_counts)
C:\Users\adead\AppData\Local\Temp\ipykernel_5820\2427318911.py:2: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  df.apply(pd.value_counts)
C:\Users\adead\AppData\Local\Temp\ipykernel_5820\2427318911.py:2: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  df.apply(pd.value_counts)
C:\Users\adead\AppData\Local\Temp\ipykernel_5820\2427318911.py:2: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  df.apply(pd.value_counts)
C:\Users\adead\AppData\Local\Temp\ipykernel_5820\2427318911.py:2: RuntimeWarning: '<' not supported between instances of 'Timestamp' and 'float', sort order is undefined for incomparable objects.
  df.apply(pd.value_counts)
C:\Users\adead\AppData\Local\Temp\ipykernel_5820\2427318911.py:2: RuntimeWarning: '<' not supported between instances of 'int' and 'Timestamp', sort order is undefined for incomparable objects.
  df.apply(pd.value_counts)
C:\Users\adead\AppData\Local\Temp\ipykernel_5820\2427318911.py:2: RuntimeWarning: '<' not supported between instances of 'int' and 'Timestamp', sort order is undefined for incomparable objects.
  df.apply(pd.value_counts)

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
-40617.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
-38046.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
-35550.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
-35262.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
-33522.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
July,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.0,NaN
February,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.0,NaN
April,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.0,NaN
May,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.0,NaN
2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,525.0